import { useState, useRef, useCallback, useEffect } from "react";
import { Camera, Upload, PenTool, Keyboard, Trash2, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import SignatureCanvas from "react-signature-canvas";
import { toast } from "sonner";
import { Camera as CapCamera } from "@capacitor/camera";
import { CameraResultType, CameraSource } from "@capacitor/camera";
import { removeBackground, loadImage } from "@/lib/backgroundRemoval";
import { useSignatures, type SavedSignature } from "@/lib/signatureStorage";
import { getProfile } from "@/lib/userProfile";
import { renderTypedSignature } from "@/lib/utils";
import { motion, AnimatePresence } from "framer-motion";

interface SignatureCreatorProps {
  onSignatureCreate?: (signature: string) => void;
  /** When true, skips method picker and goes straight to typed signature */
  quickMode?: boolean;
  /** Name to prefill in quick mode (from user profile) */
  prefillName?: string;
  /** Called when user wants to exit quick mode */
  onExitQuickMode?: () => void;
}

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.08, delayChildren: 0.1 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 16, scale: 0.97 },
  visible: { opacity: 1, y: 0, scale: 1, transition: { type: "spring", stiffness: 300, damping: 25 } },
};

const FONT_OPTIONS = [
  { value: "serif", label: "Serif", preview: "John Doe" },
  { value: "cursive", label: "Script", preview: "John Doe" },
  { value: "sans-serif", label: "Sans", preview: "John Doe" },
  { value: "monospace", label: "Mono", preview: "John Doe" },
];

export const SignatureCreator = ({ onSignatureCreate, quickMode, prefillName, onExitQuickMode }: SignatureCreatorProps) => {
  const [method, setMethod] = useState<"draw" | "photo" | "upload" | "type" | null>(quickMode ? "type" : null);
  const [signature, setSignature] = useState<string>("");
  const [saveLabel, setSaveLabel] = useState("");
  const sigCanvas = useRef<SignatureCanvas>(null);
  const { signatures: savedSignatures, addSignature, deleteSignature } = useSignatures();

  // Typed signature state
  const [typedText, setTypedText] = useState(prefillName || "");
  const [fontFamily, setFontFamily] = useState("cursive");
  const typedColor = "#1a1a1a";

  // Auto-generate in quick mode on mount only (when prefillName first arrives)
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (quickMode && prefillName && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      const dataUrl = renderTypedSignature(prefillName, fontFamily, 48, typedColor);
      setSignature(dataUrl);
      onSignatureCreate?.(dataUrl);
    }
  }, [quickMode, prefillName, fontFamily, typedColor, onSignatureCreate]);

  // Load preferred font from profile in quick mode
  useEffect(() => {
    if (quickMode) {
      getProfile().then(p => {
        if (p.preferredFont) setFontFamily(p.preferredFont);
        if (p.preferredSigColor) { /* typedColor stays for consistency */ }
      });
    }
  }, [quickMode]);

  const handleDraw = () => setMethod("draw");
  const handlePhoto = () => { setMethod("photo"); handleTakePhoto(); };
  const handleType = () => setMethod("type");

  const handleTakePhoto = async () => {
    try {
      const image = await CapCamera.getPhoto({
        quality: 90,
        allowEditing: true,
        resultType: CameraResultType.DataUrl,
        source: CameraSource.Camera,
      });
      if (image.dataUrl) await processImageWithBackgroundRemoval(image.dataUrl);
    } catch (error) {
      console.error("Camera error:", error);
      toast.error("Camera access failed. Please use upload instead.");
    }
  };

  const processImageWithBackgroundRemoval = async (dataUrl: string) => {
    const toastId = toast.loading("Removing background...");
    try {
      const response = await fetch(dataUrl);
      const blob = await response.blob();
      const img = await loadImage(blob);
      const processedBlob = await removeBackground(img);
      const reader = new FileReader();
      reader.onload = (e) => {
        const result = e.target?.result as string;
        setSignature(result);
        onSignatureCreate?.(result);
        toast.success("Signature processed successfully!", { id: toastId });
      };
      reader.readAsDataURL(processedBlob);
    } catch {
      toast.error("Failed to process image. Using original.", { id: toastId });
      setSignature(dataUrl);
      onSignatureCreate?.(dataUrl);
    }
  };

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = async (event) => {
        const result = event.target?.result as string;
        await processImageWithBackgroundRemoval(result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleClearDrawing = () => {
    sigCanvas.current?.clear();
    setSignature("");
  };

  const handleSaveDrawing = () => {
    if (sigCanvas.current) {
      const dataUrl = sigCanvas.current.toDataURL();
      setSignature(dataUrl);
      onSignatureCreate?.(dataUrl);
      toast.success("Signature saved!");
    }
  };

  const handleGenerateTyped = useCallback(() => {
    if (!typedText.trim()) {
      toast.error("Please enter your name");
      return;
    }
    const dataUrl = renderTypedSignature(typedText.trim(), fontFamily, 48, typedColor);
    setSignature(dataUrl);
    onSignatureCreate?.(dataUrl);
    setMethod(null);
    toast.success("Typed signature created!");
  }, [typedText, fontFamily, typedColor, onSignatureCreate]);

  const handleSelectSaved = (saved: SavedSignature) => {
    setSignature(saved.dataUrl);
    onSignatureCreate?.(saved.dataUrl);
    toast.success(`Using "${saved.label}"`);
  };

  const handleSaveToLibrary = async () => {
    const label = saveLabel.trim() || `Signature ${savedSignatures.length + 1}`;
    await addSignature(signature, label);
    setSaveLabel("");
    toast.success(`Signature "${label}" saved to library!`);
  };

  const isCurrentSaved = savedSignatures.some(s => s.dataUrl === signature);

  const handleDeleteSaved = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    await deleteSignature(id);
    toast.success("Signature removed from library");
  };

  const showTitle = !quickMode;
  
  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="w-full max-w-md mx-auto p-6 space-y-6"
    >
      {showTitle && (
        <motion.div variants={itemVariants}>
          <h1 className="text-3xl font-bold text-foreground tracking-tight">Create Signature</h1>
          <p className="text-muted-foreground text-sm mt-2">Choose how you'd like to create your signature</p>
        </motion.div>
      )}
      {quickMode && (
        <motion.div variants={itemVariants} className="text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold mb-1">
            Quick Sign
          </div>
          <p className="text-muted-foreground text-sm">Confirm or customize your signature</p>
        </motion.div>
      )}

      {savedSignatures.length > 0 && (
        <motion.div variants={itemVariants} className="space-y-2">
          <h3 className="text-sm font-medium text-muted-foreground">My Signatures</h3>
          <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-thin">
            {savedSignatures.map((saved) => (
              <motion.div
                key={saved.id}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => handleSelectSaved(saved)}
                className={`relative flex-shrink-0 w-32 h-16 rounded-xl border-2 cursor-pointer transition-all p-1 flex items-center justify-center ${
                  signature === saved.dataUrl
                    ? "border-primary bg-primary/5 shadow-glow"
                    : "border-border hover:border-primary/50 bg-card/50 backdrop-blur-sm"
                }`}
              >
                <img src={saved.dataUrl} alt={saved.label} className="max-w-full max-h-full object-contain" draggable={false} />
                {signature === saved.dataUrl && (
                  <div className="absolute -top-2 -right-2 w-5 h-5 bg-primary rounded-full flex items-center justify-center shadow-glow">
                    <Check className="w-3 h-3 text-primary-foreground" />
                  </div>
                )}
                <button
                  onClick={(e) => handleDeleteSaved(e, saved.id)}
                  className="absolute -top-2 -left-2 w-5 h-5 bg-destructive text-destructive-foreground rounded-full opacity-0 hover:opacity-100 transition-all flex items-center justify-center shadow-md"
                >
                  <Trash2 className="w-3 h-3" />
                </button>
              </motion.div>
            ))}
          </div>
        </motion.div>
      )}

      <AnimatePresence mode="wait">
        {!method && !quickMode ? (
          <motion.div key="methods" variants={containerVariants} initial="hidden" animate="visible" exit={{ opacity: 0, y: -10 }} className="space-y-3">
            {/* Draw */}
            <motion.div variants={itemVariants}>
              <motion.div whileHover={{ scale: 1.02, y: -2 }} whileTap={{ scale: 0.98 }}>
                <Card className="p-4 flex items-center gap-4 cursor-pointer hover:shadow-soft transition-all duration-200 bg-white/60 backdrop-blur-xl border border-border hover:border-primary/40 group" onClick={handleDraw}>
                  <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                    <PenTool className="w-5 h-5 text-primary" />
                  </div>
                  <span className="font-medium text-foreground">Draw</span>
                </Card>
              </motion.div>
            </motion.div>

            {/* Type */}
            <motion.div variants={itemVariants}>
              <motion.div whileHover={{ scale: 1.02, y: -2 }} whileTap={{ scale: 0.98 }}>
                <Card className="p-4 flex items-center gap-4 cursor-pointer hover:shadow-soft transition-all duration-200 bg-white/60 backdrop-blur-xl border border-border hover:border-accent/40 group" onClick={handleType}>
                  <div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center group-hover:bg-accent/20 transition-colors">
                    <Keyboard className="w-5 h-5 text-accent" />
                  </div>
                  <span className="font-medium text-foreground">Type</span>
                </Card>
              </motion.div>
            </motion.div>

            {/* Take Photo */}
            <motion.div variants={itemVariants}>
              <motion.div whileHover={{ scale: 1.02, y: -2 }} whileTap={{ scale: 0.98 }}>
                <Card className="p-4 flex items-center gap-4 cursor-pointer hover:shadow-soft transition-all duration-200 bg-white/60 backdrop-blur-xl border border-border hover:border-primary/40 group" onClick={handlePhoto}>
                  <div className="w-10 h-10 rounded-xl bg-secondary/10 flex items-center justify-center group-hover:bg-secondary/20 transition-colors">
                    <Camera className="w-5 h-5 text-secondary" />
                  </div>
                  <span className="font-medium text-foreground">Take Photo</span>
                </Card>
              </motion.div>
            </motion.div>

            {/* Upload */}
            <motion.div variants={itemVariants}>
              <label htmlFor="signature-upload">
                <motion.div whileHover={{ scale: 1.02, y: -2 }} whileTap={{ scale: 0.98 }}>
                  <Card className="p-4 flex items-center gap-4 cursor-pointer hover:shadow-soft transition-all duration-200 bg-white/60 backdrop-blur-xl border border-border hover:border-accent/40 group">
                    <div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center group-hover:bg-accent/20 transition-colors">
                      <Upload className="w-5 h-5 text-accent" />
                    </div>
                    <span className="font-medium text-foreground">Upload from Gallery</span>
                  </Card>
                </motion.div>
              </label>
              <input type="file" id="signature-upload" accept="image/*" onChange={handleUpload} className="hidden" />
            </motion.div>
          </motion.div>
        ) : method === "draw" ? (
          <motion.div key="draw" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="space-y-4">
            <Card className="p-4 bg-white/60 backdrop-blur-xl border border-border">
              <SignatureCanvas ref={sigCanvas} canvasProps={{ className: "w-full h-48 bg-background rounded-xl border border-border" }} />
            </Card>
            <div className="flex gap-2">
              <Button variant="outline" onClick={handleClearDrawing} className="flex-1 rounded-xl">Clear</Button>
              <Button onClick={handleSaveDrawing} className="flex-1 bg-gradient-to-r from-primary to-secondary text-white shadow-soft rounded-xl">Save</Button>
            </div>
          </motion.div>
        ) : method === "type" ? (
          <motion.div key="type" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="space-y-4">
            <Card className="p-6 bg-white/60 backdrop-blur-xl border border-border space-y-4">
              <h3 className="text-lg font-medium">Type Your Signature</h3>

              {/* Text input */}
              <input
                type="text"
                value={typedText}
                onChange={(e) => setTypedText(e.target.value)}
                placeholder="Type your full name..."
                className="w-full px-4 py-3 rounded-xl border border-border bg-background text-foreground text-lg focus:outline-none focus:ring-2 focus:ring-ring transition-all"
                autoFocus
                onKeyDown={(e) => { if (e.key === "Enter") handleGenerateTyped(); }}
              />

              {/* Font selection */}
              <div>
                <p className="text-xs text-muted-foreground mb-2">Font Style</p>
                <div className="flex gap-2">
                  {FONT_OPTIONS.map((f) => (
                    <button
                      key={f.value}
                      onClick={() => setFontFamily(f.value)}
                      className={`flex-1 px-3 py-2 rounded-lg border text-sm transition-all font-${f.value === "cursive" ? "[cursive]" : f.value === "serif" ? "serif" : f.value === "monospace" ? "mono" : "sans"}`}
                      style={{ fontFamily: f.value }}
                    >
                      <span className={fontFamily === f.value ? "text-primary font-semibold" : "text-muted-foreground"}>
                        {f.label}
                      </span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Live preview */}
              {typedText && (
                <div className="rounded-xl border border-border bg-background/50 p-4 flex items-center justify-center min-h-[80px]">
                  <span style={{ fontFamily, fontSize: 36, color: typedColor }}>{typedText}</span>
                </div>
              )}

              <div className="flex gap-2">
                {quickMode ? (
                  <Button variant="outline" onClick={onExitQuickMode} className="flex-1 rounded-xl">Back</Button>
                ) : (
                  <Button variant="outline" onClick={() => setMethod(null)} className="flex-1 rounded-xl">Back</Button>
                )}
                <Button onClick={() => { handleGenerateTyped(); if (quickMode) setMethod(null); }} className="flex-1 bg-gradient-to-r from-accent to-warning text-white shadow-soft rounded-xl">
                  {quickMode ? "Confirm" : "Generate"}
                </Button>
              </div>
            </Card>
          </motion.div>
        ) : (
          <motion.div key="photo" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="space-y-4">
            <div className="bg-white/60 backdrop-blur-xl rounded-xl border border-border p-4 flex flex-col items-center justify-center">
              <h3 className="text-lg font-medium mb-3">Take a Photo</h3>
              <div className="w-full max-w-2xl h-64 bg-black/60 rounded-lg overflow-hidden flex items-center justify-center">
                {signature ? <img src={signature} alt="Signature Preview" className="max-h-full object-contain" /> : <div className="text-sm text-muted-foreground">No photo yet</div>}
              </div>
              <div className="mt-4 flex gap-2">
                <Button onClick={handleTakePhoto} className="bg-gradient-to-r from-primary to-secondary text-white shadow-soft rounded-xl">Open Camera</Button>
                <label htmlFor="signature-upload-photo"><Button variant="outline" className="rounded-xl">Upload Photo</Button></label>
                <input type="file" id="signature-upload-photo" accept="image/*" onChange={handleUpload} className="hidden" />
              </div>
              <p className="text-xs text-muted-foreground mt-3">Background is removed automatically</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {signature && !method && (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}>
            <Card className="p-6 bg-white/60 backdrop-blur-xl border border-border">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-medium text-muted-foreground">Active Signature</h3>
              </div>
              <div className="bg-background/50 rounded-xl p-4 flex items-center justify-center min-h-[120px] border border-border">
                <img src={signature} alt="Signature" className="max-w-full max-h-40 object-contain" />
              </div>
              {!isCurrentSaved && (
                <div className="mt-4 space-y-2">
                  <input type="text" value={saveLabel} onChange={(e) => setSaveLabel(e.target.value)} placeholder="Label (e.g. My Signature)" className="w-full px-3 py-2 rounded-xl border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring transition-all" />
                  <Button onClick={handleSaveToLibrary} className="w-full" variant="outline">Save to My Signatures</Button>
                </div>
              )}
            </Card>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {method && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
            <Button variant="outline" onClick={() => { setMethod(null); if (!signature) setSignature(""); }} className="w-full">Back to Methods</Button>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};
